version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgrespassword

  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "graphql_engine_eventlog"
      INFLUXDB_ADMIN_USER: "hasura"
      INFLUXDB_ADMIN_PASSWORD: "influx_password"

  graphql-bench:
    image: finleymcilwaine/graphql-bench:main
    restart: always
    environment:
      ## postgres database to store Hasura data
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## hasura instance
      HASURA_URL: "http://graphql-engine:8080"
    command: sleep 1000s

  graphql-engine:
    image: finleymcilwaine/graphql-engine:main
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      influxdb:
        condition: service_started
    environment:
      ## postgres database to store Hasura data
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres

      ## enable the console served by server
      ##
      ## Console assets are currently broken, disabling
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console

      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

      ## enable eventlog socket
      HASURA_GHC_EVENTLOG_SOCKET: "true"
      GHC_EVENTLOG_SOCKET: /tmp/ghc-eventlog-socket

      ## eventlog-influxdb env vars
      GHC_EVENTLOG_INFLUXDB_HOST: "influxdb"
      GHC_EVENTLOG_INFLUXDB_DB: "graphql_engine_eventlog"
      GHC_EVENTLOG_INFLUXDB_USERNAME: "hasura"
      GHC_EVENTLOG_INFLUXDB_PASSWORD: "influx_password"

    command: "graphql-engine serve +RTS -l-agu --eventlog-flush-interval=1"
