# # config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: graphql_engine_eventlog
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: hasura
    jsonData:
      httpMode: POST
    secureJsonData:
      basicAuthPassword: influx_password
